web:
  build: .
  working_dir: /data
  command: python3 app.py
  links:
    - db
  volumes:
    - .:/data
  ports:
    - "5001:5001"

db:
  image: mysql:5.7
  environment:
      MYSQL_ROOT_PASSWORD: mudar123
  ports:
    - "3309:3309"